CUDA_VISIBLE_DEVICES=0, python main_test.py \
--n_gpu 1 \
--image_dir data/mimic_cxr/images/ \
--ann_path data/mimic_cxr/mimic_annotation_promptmrg.json \
--dataset_name mimic_cxr \
--gen_max_len 150 \
--gen_min_len 100 \
--batch_size 16 \
--save_dir results/promptmrg \
--seed 456789 \
--clip_k 21 \
--beam_size 3 \
--load_pretrained results/promptmrg/model_best.pth
